// ==UserScript==
// @name         Notion-Translate
// @namespace    http://tampermonkey.net/
// @version      0.3.1
// @description  Truns Notion to local language
// @author       L1n3
// @match        *://www.notion.so/*
// @grant        none
// ==/UserScript==
(function () {
  'use strict';

  function I18N() {
    this.lang = 'en';
  }

  I18N.prototype.install = function (langName, keymap) {
    if (this[langName] === undefined) {
      this[langName] = keymap;
    }
  };

  const I18n = new I18N();

  I18n.install('ru', {
    // Общее
    'Empty': 'Пусто',
    'Yesterday': 'Вчера',
    'Today': 'Сегодня',
    'Cancel': 'Отмена',
    'Delete': 'Удалить',
    'Duplicate': 'Дублировать',
    'Undo': 'Отменить',
    'Remove': 'Удалить',
    'Submit': 'Подтвердить',
    'Select': 'Выбрать',
    'Open': 'Открыть',
    'All': 'Все',
    'Refresh': 'Обновить',
    'Close': 'Закрыть',
    'Off': 'Выключено',
    'Update': 'Обновить',
    // -------------
    // Выбор рабочего пространства
    'Free Plan': 'Бесплатная версия',
    "Personal (Education) Plan": 'Персональный (образовательный) план',
    'Join or create workspace': 'Создать или присоединиться к рабочему пространству',
    "Windows App": 'Windows приложение',
    "Mobile App": 'Мобильное приложение',
    "Web Clipper": 'Расширение браузера',
    'Log out': 'Выйти',
    'member': 'участник',
    'Guest': 'Гость',
    'Create work account': 'Создать рабочий аккаунт',
    'Add another account': 'Добавить другой аккаунт',

    // -----------------
    // Левый столбец
    'Updates': 'Обновления',
    'Settings & members': 'Настройки',
    'Search': 'Поиск',
    'New page': 'Новая страница',
    'Favorites': 'Избранные',
    'No pages inside': 'Нет страниц внутри',
    'Remove from Favorites': 'Удалить из избранного',
    'Rename': 'Переименовать',
    'Open in new tab': 'Открыть в новой вкладке',
    'Open in side peek': 'Открыть в боковой панели',
    'Copy link': "Скопировать ссылку",
    'Move to': 'Переместить',
    'Private': 'Частное',
    'Create a teamspace': 'Создать командное пространство',
    'Templates': 'Шаблоны',
    'Import': 'Импорт',
    'Trash': 'Корзина',
    // -----------------
    // Меню страницы
    'Share': 'Поделиться',
    'View all comments': 'Посмотреть все комментарии',
    'View all updates': 'Посмотреть все изменения',
    'Remove from your favorites': 'Удалить из избранного',
    'Style, export, and more…': 'Стили, экспорт и др...',
    'Style': 'Стиль',
    'Default': 'По-умолчанию',
    'Small text': 'Мелкий текст',
    'Full width': 'На всю ширину',
    'Customize page': 'Изменить страницу',
    'Lock page': 'Заблокировать страницу',
    'Get notified': 'Получать уведомления',
    'All updates': 'Все изменения',
    'All comments': 'Все комментарии',
    'Replies and @mentions': 'Ссылки и @упоминания',
    'All comments and property changes': 'Все комментарии и изменения свойств',
    'Page history': 'История страницы',
    'Page analytics': 'Аналика страницы',
    'View analytics': 'Посмотреть аналитику',
    'Privacy settings': 'Настройки приватности',
    'Show deleted pages': 'Показать удаленные страницы',
    'Export': 'Экспорт',
    'Add connections': 'Добавить интеграции',
    'Edited by ': 'Отредактировал ',
    'Created by ': 'Добавил ',
    'Share or publish to the web': 'Поделиться или опубликовать в интернете',
    // -----------------
    // История страницы
    'Restore version': 'Восстановить',
    'Learn about page history': 'Документация об истории версий',
    // -----------------
    // Поиск
    'Sort': 'Сортировка',
    'Title only': 'Только заголовки',
    'Created by': 'Создал',
    'In': 'В',
    'Date': 'Дата',
    // ----------------
    // Обновления
    'Updates for all pages in this workspace': 'Обновления для всех страниц в этом рабочем пространстве',
    'Inbox': 'Входящие',
    'Archived': 'Архивные',
    'Mark all as read': 'Отметить все как прочитанные',
    'Archive all': 'Архивировать все',
    'Your workspace export is ready': 'Ваше рабочее пространство готово',
    'The download link will expire in 7 days.': 'Ссылка скачивания истекает через 7 дней',
    'Download': 'Скачать',
    'Archive this notification': 'Архивировать это уведомление',
    'Mark this notification as unread': 'Отметить это уведомление как непрочитанное',
    'All notifications have been marked as read.': 'Все уведомления отмечены как прочитанные',
    'Show unread notifications only': 'Показать только непрочитанные уведомления',
    'Open notifications settings': 'Открыть настройки уведомлений',
    'Learn more about notifications': 'Прочитать больше про уведомления',
    'No archived updates': 'Нет архивных обновлений',
    'Any Inbox updates you archived will show up here.': 'Здесь будут отображаться любые заархивированные вами обновления папки «Входящие»',
    // -----------------
    // Регистрация
    'Continue with email': 'Продолжить с email',
    'Sign up': 'Регистрация',
    'Work email': 'Рабочий email',
    'You can also ': 'Вы можете также ',
    'continue with SAML SSO': 'продолжить с SAML SSO',
    'Continue with Google': 'Продолжить с Google',
    'Continue with Apple': 'Продолжить с Apple',
    'Enter your email address…': 'Введите ваш email адрес',
    'By clicking “Continue with Apple/Google/Email/SAML” above, you acknowledge that you have read and understood, and agree to Notion\'s ': 'Нажимая «Продолжить с Apple/Google/Email/SAML» выше, вы подтверждаете, что прочитали и поняли, а также соглашаетесь с условиями Notion. ',
    'Terms & Conditions': 'Условия использования',
    ' and ': ' и ',
    'Privacy Policy': 'Политика конфиденциальности',
    // ---------------
    // Настройки
    'Account': 'Аккаунт',
    'My account': 'Мой аккаунт',
    'My notifications & setting': 'Мои уведомления и настройки',
    'My connections': 'Мои интеграции',
    'Language & region': 'Язык и регион',
    'Workspace': 'Рабочее пространство',
    'Settings': 'Настройки',
    'Members': 'Участники',
    'Upgrade': 'Улучшить',
    'Security': 'Безопасность',
    'Identity & provisioning': 'Идентификация и подготовка',
    'Connections': 'Интеграции',
    'Groups': 'Группы',
    'Guests': 'Гости',
    'My settings': 'Мои настройки',
    'My notifications': 'Мои уведомления',
    'New': 'Новое',
    'Learn about adding members to your workspace': 'Узнайте о добавлении участников в вашу рабочее пространство',
    'Invite link': 'Ссылка для приглашения',
    'Share this secret link to invite people to this workspace. Only users who can invite members can see this.': 'Поделитесь этой секретной ссылкой, чтобы пригласить людей в это рабочее пространство. Это смогут увидеть только пользователи, которые могут приглашать участников.',
    'You can ': 'Вы можете ',
    'reset the link': 'сбросить ссылку',
    ' for all space members to generate a new invite link.': ' всем участникам пространства и создать новую ссылку для приглашения.',
    'Manage members here.': 'Управление участниками здесь',
    'Add members': 'Добавить участников',
    'Filter by email or name…': 'Фильтр по email или имени',
    'User': 'Пользователь',
    'Pages': 'Страницы',
    'Workspace owner': 'Владелец рабочего пространства',
    'Can change workspace settings and invite new members to the workspace.': 'Может изменять настройки рабочей области и приглашать в нее новых участников.',
    'Member': 'Участник',
    'Cannot change workspace settings or invite new members to the workspace.': 'Невозможно изменить настройки рабочей области или пригласить в нее новых участников.',
    'Leave workspace': 'Покинуть рабочее пространство',
    'Search name or emails': 'Поиск по имени или email',
    'Invite': 'Пригласить',
    'Select a person': 'Выберите персону',
    'Learn how to invite people and set permissions': 'Узнайте, как приглашать людей и устанавливать разрешения',
    'Select a person': 'Выберите персону',
    'Upgrade to create groups': 'Обновите, чтобы создавать группы',
    'Upgrade to the Plus Plan to set up groups and control permissions from the share menu.': 'Перейдите на план Plus, чтобы настраивать группы и управлять разрешениями из меню общего доступа.',
    'Learn more': 'Узнать больше',
    'Change who can invite guests in the ': 'Измените, кто может приглашать гостей в ',
    'View settings': 'Посмотреть настройки',
    'Manage your account and settings': 'Управление вашим аккаунтом и настройки',
    'My profile': 'Мой профиль',
    'Preferred name': 'Имя',
    'Account security': 'Безопасность аккаунта',
    'Change email': 'Изменить email',
    'Password': 'Пароль',
    'Set a permanent password to login to your account.': 'Установите постоянный пароль для входа в свою учетную запись.',
    '2-step verification': '2-факторная верификация',
    'Add an additional layer of security to your account during login.': 'Добавьте дополнительный уровень безопасности в свою учетную запись во время входа в систему.',
    'Support': 'Поддержка',
    'Something went wrong': 'Что-то пошло не так',
    'Log out of all devices': 'Выйти на всех устройствах',
    'Log out of all other active sessions on other devices besides this one.': 'Выйдите из всех активных сеансов на других устройствах, кроме этого.',
    'Delete my account': 'Удалите мой аккаунт',
    'Permanently delete the account and remove access from all workspaces.': 'Удалите учетную запись навсегда и закройте доступ ко всем рабочим пространствам.',
    'Support access': 'Поддержка доступа',
    'Grant Notion support temporary access to your account so we can troubleshoot problems or recover content on your behalf. You can revoke access at any time.': 'Предоставьте Notion поддержку временного доступа к вашей учетной записи, чтобы мы могли устранять проблемы или восстанавливать контент от вашего имени. Вы можете запретить доступ в любое время.',
    'A password is required to enable 2-step verification': 'Для включения двухэтапной аутентификации необходим пароль',
    'Your current email is ': 'Ваш текущий адрес электронной почты',
    'We\'ll send a temporary verification code to this email.': 'На это письмо мы отправим временный код подтверждения.',
    'Send verification code': 'Отправить код подтверждения',
    'This action cannot be undone. This will permanently delete your entire account. All private workspaces will be deleted, and you will be removed from all shared workspaces.': 'Это действие не может быть отменено. Это приведет к безвозвратному удалению всей вашей учетной записи. Все частные рабочие области будут удалены, а вы будете удалены из всех общих рабочих областей.',
    'Please type in your email to confirm.': 'Пожалуйста, введите свой адрес электронной почты для подтверждения.',
    'Permanently delete account and 1 workspace': 'Удалить учетную запись и 1 рабочее пространство навсегда',
    'Appearance': 'Внешний вид',
    'Customize how Notion looks on your device.': 'настройте внешний вид Notion на вашем устройстве.',
    'Use system setting': 'Использовать системные настройки',
    'Light': 'Светлая',
    'Dark': 'Темная',
    'Open on start': 'Открыть при запуске',
    'Choose what to show when Notion starts or when you switch workspaces.': 'Выберите, что показывать при запуске Notion или при переключении рабочих пространств.',
    'Last visited page': 'Последняя посещенная страница',
    'Top page in sidebar': 'Верхняя страница на боковой панели',
    'Open links in desktop app': 'Открытие ссылок в desktop приложении',
    'You must have the ': 'У вас должно быть ',
    'Mac or Windows app': 'Mac или Windows приложение',
    ' installed': 'установлено',
    'Date & time': 'Дата и время',
    'Set timezone automatically using your location': 'Установите часовой пояс автоматически, используя ваше местоположение',
    'Reminders, notifications and emails are delivered based on your time zone.': 'Напоминания, уведомления и электронные письма доставляются в зависимости от вашего часового пояса.',
    'Time Zone': 'Часовой пояс',
    'Current time zone setting.': 'Текущая настройка часового пояса.',
    'Privacy': 'Приватность',
    'Cookie settings': 'Настройки куки',
    'Customize cookies. See': 'Настраивайте куки. Смотрите',
    'Cookie Notice': 'Статью о куки',
    'for details.': 'чтобы узнать подробности',
    'Strictly necessary': 'Строго необходимо',
    'Essential for the site to function. Always On.': 'Необходим для работы сайта. Всегда включен.',
    'Functional': 'Функциональный',
    'Used to remember preference selections and provide enhanced features.': 'Используется для запоминания выбранных предпочтений и предоставления расширенных функций.',
    'Analytics': 'Аналитика',
    'Used to measure usage and improve your experience.': 'Используется для измерения использования и улучшения вашего опыта.',
    'Marketing': 'Маркетинг',
    'Used for targeted advertising.': 'Используется для таргетированной рекламы.',
    'Customize': 'Изменить',
    'Show my view history': 'Показать мою историю просмотров',
    'People with edit or full access will be able to see when you’ve viewed a page. ': 'Люди с правами редактирования или полным доступом смогут видеть, когда вы просматривали страницу.',
    'Record': 'Записывать',
    'Don\'t record': 'Не записывать',
    'Mobile push notifications': 'Мобильные пуш уведомления',
    'Receive push notifications on mentions and comments via your mobile app': 'Получайте push-уведомления об упоминаниях и комментариях через мобильное приложение.',
    'Slack notifications': 'Уведомления в Slack',
    'Receive notifications in your Slack workspace when you\'re mentioned in a page, database property, or comment': 'Получайте уведомления в своем рабочем пространстве Slack, когда вас упоминают на странице, в свойстве базы данных или в комментарии.',
    'Add new account': 'Добавить новый аккаунт',
    'Email notifications': 'Email уведомления',
    'Activity in your workspace': 'Активность на вашем рабочем месте',
    'Receive emails when you get comments, mentions, page invites, reminders, access requests, and property changes': 'Получайте электронные письма, когда вы получаете комментарии, упоминания, приглашения на страницы, напоминания, запросы на доступ и изменения свойств.',
    'Email digests': 'Дайджесты электронной почты',
    'Receive email digests every 8 hours for changes to pages you’re subscribed to': 'Получайте дайджесты по электронной почте каждые 8 часов об изменениях на страницах, на которые вы подписаны.',
    'Announcements and update emails': 'Объявления и обновления по электронной почте',
    'Receive occasional emails about product launches and new features from Notion': 'Периодически получайте электронные письма о выпусках продуктов и новых функциях Notion.',
    'Manage settings': 'Управление настройками',
    'Learn about notifications': 'Подробнее об уведомлениях',
    'Connection': 'Интеграция',
    'Access': 'Доступ',
    'Can': 'Может',
    'view': 'просматривать',
    'insert': 'добавлять',
    ', and': ', и',
    'update': 'изменять',
    ' content': ' контент',
    'preview links': 'ссылки для предварительного просмотра',
    'sync databases': 'синхронизировать базы данных',
    'Discover new connections': 'Откройте для себя новые интеграции',
    'Connect': 'Соединить',
    'See all': 'Посмотреть все',
    'View the latest updates from GitLab in Notion pages and databases': 'Просматривайте последние обновления GitLab на страницах и базах данных Notion.',
    'Enable everyone in your workspace to link PRs in databases and automate workflows': 'Предоставьте возможность всем в вашем рабочем пространстве связывать PR в базах данных и автоматизировать рабочие процессы.',
    'Embed dynamic dashboards, interactive charts, data visualizations, and calculators in Notion.': 'Встраивайте в Notion динамические информационные панели, интерактивные диаграммы, визуализацию данных и калькуляторы.',
    'Browse connections in Gallery': 'Просмотр интеграций в Галерее',
    'Develop or manage integrations': 'Разрабатывайте или управляйте интеграциями',
    'Learn more about connections': 'Узнайте больше о подключениях',
    'View the latest updates from Jira in Notion pages and databases': 'Просматривайте последние обновления Jira на страницах и базах данных Notion.',
    'Language': 'Язык',
    'Change the language used in the user interface.': 'Измените язык, используемый в пользовательском интерфейсе.',
    'Start week on Monday': 'Начало недели в понедельник',
    'This will change how all calendars in your app look.': 'Это изменит внешний вид всех календарей в вашем приложении.',
    'Workspace settings': 'Настройки рабочей области',
    'Name': 'Название',
    'e.g. company name': 'например название компании',
    'You can use your organization or company name. Keep it simple.': 'Вы можете использовать название вашей организации или компании.',
    'Icon': 'Иконка',
    'Upload an image or pick an emoji. It will show up in your sidebar and notifications.': 'Загрузите изображение или выберите смайлик. Он будет отображаться на вашей боковой панели и в уведомлениях.',
    'Public settings': 'Настройки публичности',
    'Domain': 'Домен',
    'Your domain': 'Ваш домен',
    'Pages shared to web will be under ': 'Страницы, опубликованные в Интернете, будут находиться под ',
    'Anyone with an allowed email domain can join this workspace via ': 'Любой, у кого разрешен домен электронной почты, может присоединиться к этому рабочему пространству через ',
    'Allowed email domains': 'Разрешенные домены электронной почты',
    'Type an email domain…': 'Введите домен электронной почты…',
    'Anyone with email addresses at these domains can automatically join your workspace.': 'Любой, у кого есть адреса электронной почты в этих доменах, может автоматически присоединиться к вашему рабочему пространству.',
    'Public home page': 'Публичная домашняя страница',
    'Select a page shared to web': 'Выберите страницу, опубликованную в Интернете',
    'Access your public home page via ': 'Получите доступ к общедоступной домашней странице через ',
    'Export content': 'Экспортировать контент',
    'Export all workspace content': 'Экспортировать все содержимое рабочей области',
    'Learn about exporting workspaces.': 'Узнайте об экспорте рабочих пространств.',
    'Export members': 'Экспортировать участников',
    'Export members as CSV': 'Экспортировать участников в формате CSV',
    'Learn about exporting members.': 'Узнайте об экспорте участников.',
    'Save and display page view analytics': 'Сохранение и отображение аналитики просмотра страниц',
    'Learn about workspace analytics.': 'Узнайте об аналитике рабочего пространства.',
    'Danger zone': 'Зона опасности',
    'Delete entire workspace': 'Удалить всю рабочую область',
    'Learn about deleting workspaces.': 'Узнайте об удалении рабочих областей.',
    // ---------------
    // Страница
    'Change cover': 'Изменить изображение',
    'Reposition': 'Позиция',
    'Save position': 'Сохранить позицию',
    'Drag image to reposition': 'Перетащите изображение чтобы изменить позицию',
    'Gallery': 'Галерея',
    'Upload': 'Загрузить',
    'Link': 'Ссылка',
    'Upload file': 'Загрузить файл',
    'Images wider than 1500 pixels work best.': 'Рекомендуется загружать изображения более 1500 пикселей',
    'The maximum size per file is 5 MB.': 'Максимальный размер 5 мб',
    'Paste an image link…': 'Вставьте ссылку на изображение',
    'Works with any image from the web.': 'Работает с любыми изображениями из интернета',
    'Search for an image…': 'Поиск изображений',
    '3 more properties': 'Еще 3 поля',
    '2 more properties': 'Еще 2 поля',
    '1 more property': 'Еще 1 поле',
    'Create a new page': 'Создать новую страницу',
    'Add icon': 'Добавить иконку',
    'Untitled': 'Без названия',
    'Add to': 'Добавить к',
    'Private pages': 'Приватные страницы',
    'Add cover': 'Добавить изображение',
    'Empty page': 'Пустая страница',
    'Start writing with AI…': 'Начать с использованием ИИ',
    'Add new': 'Добавить новое',
    'Import': 'Импорт',
    'Table': 'Таблица',
    'More': 'Больше',
    'Add comment': 'Добавить комментарий',
    'Add to Favorites': 'Добавить в избранное',
    'Color': 'Цвет',
    'Turn into wiki': 'Превратить в вики',
    'Organize by owner, tags, verification, and more': 'Упорядочить по владельцу, тегам, проверке и т.д.',
    'Open in Mac app': 'Открыть в приложении Mac',
    'Open in Windows app': 'Открыть в приложении Windows',
    'Manage connections': 'Управлять интеграциями',
    'Turn into page in': 'Превратить страницу в',
    'Emojis': 'Эмодзи',
    'Custom': 'Другое',
    'Filter…': 'Фильтровать...',
    'People': 'Люди',
    'Animals and nature': 'Животные и природа',
    'Food and drink': 'Еда и напитки',
    'Activity': 'Активность',
    'Travel and places': 'Путешествия и места',
    'Objects': 'Объекты',
    'Symbols': 'Символы',
    'Flags': 'Флаги',
    'Recommended size is 280 × 280 pixels': 'Рекомендуемый размер — 280 × 280 пикселей.',
    'Paste link to an image...': 'Вставить ссылку на изображение...',
    'Add a property': 'Добавить поле',
    'Configure rollup': 'Настроить объединение',
    'Unlink page': 'Отсоединить страницу',
    'Link another page': 'Связать другую страницу',
    'Copy to Clipboard': 'Копировать в буфер обмена',
    'Edit property': 'Изменить поле',
    'Property visibility': 'Видимость поля',
    'Duplicate property': 'Дублировать поле',
    'Delete property': 'Удалить поле',
    // --------------
    // Цвета
    'A': 'A',
    'Gray': 'Серый',
    'Brown': 'Коричневый',
    'Orange': 'Оранжевый',
    'Yellow': 'Желтый',
    'Blue': 'Синий',
    'Purple': 'Фиолетовый',
    'Pink': 'Розовый',
    'Red': 'Красный',
    'Background': 'Фон',
    'Green': 'Зеленый',
    'Default background': 'Фон по-умолчанию',
    'Gray background': 'Серый фон',
    'Brown background': 'Коричневый фон',
    'Orange background': 'Оранжевый фон',
    'Yellow background': 'Желтый фон',
    'Blue background': 'Синий фон',
    'Purple background': 'Фиолетовый фон',
    'Pink background': 'Розовый фон',
    'Red background': 'Красный фон',
    'Green background': 'Зеленый фон',
    // --------------
    // Блоки
    'Page': 'Страница',
    'Icons': 'Иконки',
    'Text': 'Текст',
    'Heading 1': 'Заголовок 1',
    'Heading 2': 'Заголовок 2',
    'Heading 3': 'Заголовок 3',
    'To-do list': 'Список дел',
    'Bulleted list': 'Маркированный список',
    'Numbered list': 'Нумерованный список',
    'Toggle list': 'Раскрывающийся список',
    'Code': 'Код',
    'Quote': 'Цитата',
    'Callout': 'Выноска',
    'Block equation': 'Математический блок',
    'Toggle heading 1': 'Раскрывающийся заголовок 1',
    'Toggle heading 2': 'Раскрывающийся заголовок 2',
    'Toggle heading 3': 'Раскрывающийся заголовок 3',
    '2 columns': '2 столбца',
    '3 columns': '3 столбца',
    '4 columns': '4 столбца',
    '5 columns': '5 столбцов',
    'Basic blocks': 'Основные блоки',
    'Just start writing with plain text.': 'Просто начните писать с обычного текста.',
    'Embed a sub-page inside this page.': 'Вставьте подстраницу внутрь этой страницы.',
    'Track tasks with a to-do list.': 'Отслеживайте задачи с помощью списка дел.',
    'Big section heading.': 'Большой заголовок раздела.',
    'Medium section heading.': 'Средний заголовок раздела.',
    'Small section heading.': 'Маленький заголовок раздела.',
    'Add simple tabular content to your page.': 'Добавьте на свою страницу простой табличный контент.',
    'Create a simple bulleted list.': 'Создайте простой маркированный список.',
    'Create a list with numbering.': 'Создайте список с нумерацией.',
    'Toggles can hide and show content inside.': 'Переключатели могут скрывать и показывать содержимое внутри.',
    'Capture a quote.': 'Добавьте цитату',
    'Divider': 'Разделитель',
    'Visually divide blocks.': 'Визуально разделяйте блоки.',
    'Link to page': 'Ссылка на страницу',
    'Link to an existing page.': 'Ссылка на существующую страницу.',
    'Make writing stand out.': 'Сделайте написание выдающимся.',
    'Ask AI to write...': 'Попросите ИИ написать...',
    'Continue writing': 'Продолжить писать',
    'Summarize': 'Подведем итог',
    'See more': 'Узнать больше',
    'Media': 'Медиа',
    'Image': 'Изображение',
    'Upload or embed with a link.': 'Загрузите или вставьте ссылку.',
    'Web bookmark': 'Веб-закладка',
    'Save a link as a visual bookmark.': 'Сохраните ссылку как визуальную закладку.',
    'Video': 'Видео',
    'Embed from YouTube, Vimeo...': 'Вставка с YouTube, Vimeo...',
    'Audio': 'Аудио',
    'Capture a code snippet.': 'Запишите фрагмент кода.',
    'File': 'Файл',
    'Database': 'База данных',
    'Table view': 'Табличный вид',
    'Add a table view for a new or existing database.': 'Добавьте представление таблицы для новой или существующей базы данных.',
    'Board view': 'Вид доски',
    'Create a kanban board database view.': 'Создайте представление базы данных канбан-доски.',
    'Gallery view': 'Вид галереи',
    'Create a gallery database view.': 'Создайте представление базы данных галереи.',
    'List view': 'Вид списка',
    'Create a list database view.': 'Создайте представление базы данных списка.',
    'Calendar view': 'Вид календаря',
    'Create a calendar database view.': 'Создайте представление базы данных календаря.',
    'Timeline view': 'Вид временной шкалы',
    'Create a timeline database view.': 'Создайте представление базы данных временной шкалы.',
    'Database - Inline': 'База данных — встроенная',
    'Add a new inline database to this page.': 'Добавьте на эту страницу новую встроенную базу данных.',
    'Database - Full page': 'База данных - Полная страница',
    'Add a new database as a sub-page.': 'Добавьте новую базу данных в качестве подстраницы.',
    'Linked view of database': 'Связанное представление базы данных',
    'Add an existing database to this page.': 'Добавьте существующую базу данных на эту страницу.',
    'AI blocks': 'Блоки ИИ',
    'Summary': 'Краткое содержание',
    'AI': 'ИИ',
    'Generate a summary for the current page.': 'Создайте сводку для текущей страницы.',
    'Action items': 'Пункты действий',
    'Extract action items from current page.': 'Извлечь элементы действия с текущей страницы.',
    'Custom AI Block': 'Пользовательский блок ИИ',
    'Generate content from any instruction.': 'Генерируйте контент из любой инструкции.',
    'Advanced blocks': 'Дополнительные блоки',
    'Table of contents': 'Содержание',
    'Show an outline of your page.': 'Покажите схему вашей страницы.',
    'Display a standalone math equation.': 'Отобразите отдельное математическое уравнение.',
    'Button': 'Кнопка',
    'Run custom automations with a click.': 'Запускайте пользовательскую автоматизацию одним щелчком мыши.',
    'Breadcrumb': 'Навигация',
    'Show the current page location.': 'Показать текущее местоположение страницы.',
    'Visually divide blocks.': 'Визуально разделяйте блоки.',
    'Embed from SoundCloud, Spotify...': 'Вставка из SoundCloud, Spotify...',
    'Find action items': 'Найди предметы для действий',
    'Translate': 'Перевод',
    'Explain this': 'Объясни это',
    'Improve writing': 'Улучши написанное',
    'Fix spelling & grammar': 'Исправь орфографию и грамматику',
    'Make shorter': 'Сделать короче',
    'Make longer': 'Делайте дольше',
    'Change tone': 'Изменить тон',
    'Simplify language': 'Упростить язык',
    'Ask AI to edit...': 'Попросите ИИ отредактировать...',
    'Brainstorm ideas': 'Брейншторм идей',
    'Blog post': 'Пост для блога',
    'Outline': 'Выделить',
    'Social media post': 'Пост социальных сетей',
    'Ask AI to write anything…': 'Попросите ИИ написать что-нибудь…',
    'Synced block': 'Синхронизированный блок',
    'Sync content across pages.': 'Синхронизируйте контент между страницами.',
    'Hide content inside a large heading.': 'Скройте контент внутри большого заголовка.',
    'Hide content inside a medium heading.': 'Скройте контент внутри среднего заголовка.',
    'Hide content inside a small heading.': 'Скройте контент внутри небольшого заголовка.',
    'Create 2 columns of blocks.': 'Создайте 2 столбца блоков.',
    'Create 3 columns of blocks.': 'Создайте 3 столбца блоков.',
    'Create 4 columns of blocks.': 'Создайте 4 столбца блоков.',
    'Create 5 columns of blocks.': 'Создайте 5 столбцов блоков.',
    'Code - Mermaid': 'Код - Русалка',
    'Create a diagram by writing code.': 'Создайте диаграмму, написав код.',
    'Inline': 'Инлайн',
    'Mention a person': 'Упоминание человека',
    'Ping someone so they get a notification.': 'Отправьте кому-нибудь пинг, чтобы он получил уведомление.',
    'Mention a page': 'Упоминание страницы',
    'Mention a page and place in text.': 'Упомяните страницу и поместите ее в текст.',
    'Date or reminder': 'Дата или напоминание',
    'Insert a date or reminder in text.': 'Вставьте дату или напоминание в текст.',
    'Emoji': 'Эмодзи',
    'Search for an emoji to place in text.': 'Найдите смайлик и поместите его в текст.',
    'Inline equation': 'Встроенное уравнение',
    'Insert mathematical symbols in text.': 'Вставляйте математические символы в текст.',
    'Embeds': 'Встраивание',
    'Embed': 'Встроить',
    'For PDFs, Google Maps, and more.': 'Для PDF-файлов, карт Google и т.д.',
    'Add previews of files.': 'Добавьте превью файлов.',
    'Embed a Tweet.': 'Вставьте твит.',
    'Embed a Gist from GitHub.': 'Вставьте Gist с GitHub.',
    'Embed a Google Map.': 'Вставьте карту Google.',
    'View Figma designs directly in Notion': 'Просматривайте проекты Figma прямо в Notion',
    'Press release': 'пресс-релиз',
    'Creative story': 'Творческая история',
    'Essay': 'Сочинение',
    'Poem': 'Стих',
    'Meeting agenda': 'Повестка дня встречи',
    'Pros and cons list': 'Список плюсов и минусов',
    'Job description': 'Описание работы',
    'Sales email': 'Электронная рассылка',
    'Recruiting email': 'Рассылка для найма',
    'Professional': 'Профессиональный',
    'Casual': 'Повседневный',
    'Straightforward': 'Простой',
    'Confident': 'Уверенный',
    'Friendly': 'Дружелюбный',
    'Embed an Abstract project.': 'Встройте Abstract проект.',
    'Embed an Invision project.': 'Встройте проект Invision.',
    'Embed a Mixpanel project.': 'Встройте проект Mixpanel.',
    'Embed a Framer prototype.': 'Встройте прототип Framer.',
    'View Whimsical boards in Notion pages': 'Просмотр Whimsical досок на страницах Notion',
    'Embed a Miro board.': 'Встройте доску Miro.',
    'Embed a Sketch document.': 'Вставьте документ Sketch.',
    'Embed an Excalidraw whiteboard.': 'Встройте доску Excalidraw.',
    'Embed a PDF.': 'Вставьте PDF',
    'Embed a Loom recording.': 'Вставьте запись Loom.',
    'Embed a Typeform.': 'Вставьте Typeform.',
    'Embed a CodePen.': 'Вставьте CodePen.',
    'Embed a repl.': 'Вставить репл.',
    'Embed Hex projects and cells in Notion': 'Встраивайте Hex-проекты и ячейки в Notion',
    'Embed a Deepnote block.': 'Вставьте блок Deepnote.',
    'Easily sync Trello cards in Notion': 'Простая синхронизация карточек Trello в Notion',
    'Notifications, live links, and workflows between Notion and Slack': 'Уведомления, живые ссылки и рабочие процессы между Notion и Slack.',
    'Bring Asana tasks into Notion to see the latest updates across teams': 'Перенесите задачи Asana в Notion, чтобы увидеть последние обновления команд.',
    'View the latest updates from GitHub in Notion pages and databases': 'Просматривайте последние обновления с GitHub на страницах и базах данных Notion.',
    'Embed live presentations to keep your team in sync.': 'Встраивайте живые презентации, чтобы синхронизировать работу вашей команды.',
    'See files from OneDrive and Sharepoint in Notion': 'Просматривайте файлы из OneDrive и Sharepoint в Notion',
    'Add and preview Dropbox files directly in Notion': 'Добавляйте и просматривайте файлы Dropbox прямо в Notion.',
    'Easily share Zoom meeting details in Notion': 'Легко делитесь подробностями собрания Zoom в Notion',
    'Preview Amplitude charts inside Notion': 'Предварительный просмотр диаграмм Amplitude внутри Notion',
    'Share videos, record meetings, collaborate and search, all in one place. View and comment on Claap videos without leaving Notion.': 'Делитесь видео, записывайте встречи, сотрудничайте и осуществляйте поиск — все в одном месте. Просматривайте и комментируйте видео Claap, не выходя из Notion.',
    'Add and preview Box files directly in Notion': 'Добавляйте и просматривайте файлы Box прямо в Notion.',
    'See live previews of Linear issues, projects, and views in Notion': 'См. предварительный просмотр линейных проблем, проектов и представлений в Notion.',
    'Share and view Lucidchart diagrams directly in Notion': 'Делитесь и просматривайте диаграммы Lucidchart прямо в Notion.',
    'Share and view Lucidspark boards directly in Notion': 'Делитесь и просматривайте доски Lucidspark прямо в Notion',
    'Preview Eraser files and diagrams in Notion': 'Предварительный просмотр файлов и диаграмм Eraser в Notion',
    'Preview PagerDuty incidents and on-call services inside your Notion projects and tasks': 'Предварительный просмотр инцидентов PagerDuty и услуг по вызову в ваших проектах и задачах Notion.',
    'Bring ClickUp tasks into Notion to see the latest updates across teams': 'Перенесите задачи ClickUp в Notion, чтобы видеть последние обновления команд.',
    'View Adobe XD files directly in Notion': 'Просмотр файлов Adobe XD непосредственно в Notion',
    'Live snapshots of any app in your Notion workspace': 'Живые снимки любого приложения в вашем рабочем пространстве Notion.',
    'Embed customer insights, projects, and data for stakeholders in Notion': 'Встраивайте информацию о клиентах, проекты и данные для заинтересованных сторон в Notion.',
    'Bring email links into Notion': 'Добавьте ссылки электронной почты в Notion',
    'View Shortcut stories, epics, milestones and docs in Notion': 'Просмотр кратких историй, эпиков, вех и документов в Notion',
    'Sell any digital product or service directly from any Notion page.': 'Продавайте любой цифровой продукт или услугу прямо с любой страницы Notion.',
    'Add previews of Zendesk tickets': 'Добавить предварительный просмотр билетов Zendesk',
    'Synced Databases': 'Синхронизированные базы данных',
    'Ask AI': 'Спросите ИИ',
    'Copy link to block': 'Скопировать ссылку на блок',
    'Comment': 'Комментировать',
    'Turn into': 'Превратить в',
    'Actions': 'Действия',
    // -------------
    // Other
    'Copied link to clipboard': 'Ссылка скопирована',
    "Add a page": "Добавить страницу",
    "Edited just now": "Отредактировано только что",
    "PDF, HTML, Markdown & CSV": "PDF, HTML, Markdown и CSV",
    "Открыть в приложении Mac": "Открыть в приложении Mac",
    "Good for drafting and notes": "Хорошо для черновиков и заметок",
    "Page notification settings": "Настройки уведомлений страницы",
    "Views": "Просмотры",
    "Viewers": "Зрители",
    "Editors": "Редакторы",
    "No updates on this page yet.": "Обновлений на этой странице пока нет.",
    "2 total views": "Всего 2 просмотра",
    "1 unique view": "1 уникальный просмотр",
    "My view history": "Моя история просмотров",
    "Page editors can see my view history for this page. ": "Редакторы страницы могут видеть мою историю просмотров этой страницы.",
    "Close sidebar": "Закрыть боковую панель",
    "Lock sidebar open": "Закрепить боковую панель",
    "Manage members here, or ": "Управляйте участниками здесь или ",
    "set up a domain": "настройте домен",
    ", so everyone with allowed email domains can join the workspace automatically.": ", чтобы все с разрешенными доменами электронной почты могли присоединиться к рабочему пространству автоматически.",
    "You will be charged for each member added. Visit ": "Вам будет начисляться оплата за каждого добавленного участника. Посетите ",
    "our guide": "наше руководство",
    " for more information on how we bill.": " для получения дополнительной информации о том, как мы выставляем счета.",
    "Import from Slack": "Импорт из Slack",
    "English": "Английский",
    "Set your own": "Установите свой",
    "Current plan": "Текущий план",
    " / member / month": " / участник / месяц",
    "1 active member": "1 активный участник",
    "Includes": "Включает",
    "Unlimited blocks for individuals": "Неограниченное количество блоков для физических лиц",
    "Collaborative workspace": "Совместное рабочее пространство",
    "Slack, GitHub, and more integrations": "Slack, GitHub и другие интеграции",
    "7 day page history": "7-дневная история страницы",
    "Invite up to 10 guests": "Пригласите до 10 гостей",
    "Notion AI": "Notion AI",
    "0/20 AI responses used": "0/20 использованных ответов AI",
    "Use AI responses to generate docs, autofill your databases, and improve your writing. Add AI to your plan to go unlimited.": "Используйте ответы AI для создания документов, автозаполнения баз данных и улучшения письма. Добавьте AI в свой план, чтобы получить неограниченные возможности.",
    "Purchase AI": "Приобрести AI",
    "Other plans to consider": "Другие планы для рассмотрения",
    "See all plans": "Посмотреть все планы",
    "Plus Plan": "План Plus",
    "Everything in Free, and": "Все, что есть в Free, и",
    "Unlimited blocks for teams": "Неограниченное количество блоков для команд",
    "Unlimited file uploads": "Неограниченная загрузка файлов",
    "30 day page history": "30-дневная история страницы",
    "Business Plan": "Бизнес-план",
    "Everything in Plus, and": "Все, что есть в Plus, и",
    "SAML SSO": "SAML SSO",
    "Private Teamspaces": "Частные рабочие пространства",
    "Bulk PDF export": "Массовый экспорт в формате PDF",
    "90 day page history": "90-дневная история страницы",
    "Invite up to 250 guests": "Пригласите до 250 гостей",
    "Enterprise Plan": "План Enterprise",
    "Everything in Business, and": "Все, что есть в Business, и",
    "Unlimited page history": "Неограниченная история страницы",
    "Custom guest limits": "Настройка ограничений для гостей",
    "User provisioning (SCIM)": "Предоставление прав пользователей (SCIM)",
    "Advanced security controls": "Расширенные средства безопасности",
    "Audit log": "Журнал аудита",
    "Customer success manager": "Менеджер по работе с клиентами",
    "billed monthly": "оплачивается ежемесячно",
    "Upgrade for SAML SSO & more admin tools": "Обновление для SAML SSO и дополнительных инструментов администратора",
    "The Business Plan includes single sign-on to manage employee access at scale, private teamspaces to collaborate on sensitive docs, and more.": "Бизнес-план включает в себя единовременную аутентификацию для управления доступом сотрудников в масштабе, частные командные пространства для совместной работы над конфиденциальными документами и многое другое.",
    "Upgrade to Business": "Повысьте до Бизнес",
    "Upgrade for SCIM, advanced security & more": "Обновление для SCIM, продвинутой безопасности и многого другого",
    "The Enterprise Plan allows you to automatically provision users and groups, and gain more visibility and controls across the workspace.": "План Enterprise позволяет автоматически предоставлять пользователей и группы, а также обеспечивает большую видимость и контроль в рабочем пространстве.",
    "Upgrade to Enterprise": "Повысьте до Enterprise",
    "General": "Общие",
    "Disable public page sharing": "Отключить общий доступ к страницам",
    "Disable the Share to web option in the Share menu on every page in this workspace.": "Отключить опцию «Поделиться в вебе» в меню «Поделиться» на каждой странице в этом рабочем пространстве.",
    "Prevent members from editing the Workspace section": "Запретить участникам редактирование раздела Рабочего пространства",
    "Disable the ability for members to create, move, reorder, and delete top-level Workspace pages.": "Отключить возможность для участников создавать, перемещать, изменять порядок и удалять страницы верхнего уровня Рабочего пространства.",
    "Disable duplicating pages to other workspaces": "Отключить копирование страниц в другие рабочие пространства",
    "Prevent anyone from duplicating pages to other workspaces via the Move To or Duplicate To actions.": "Запретить копирование страниц в другие рабочие пространства с использованием действий Переместить в или Дублировать в.",
    "Disable export": "Отключить экспорт",
    "Prevent anyone from exporting as Markdown, CSV, or PDF.": "Запретить экспорт в форматах Markdown, CSV или PDF.",
    "Inviting members & guests": "Приглашение участников и гостей",
    "Disable members inviting guests to pages": "Отключить возможность участникам приглашать гостей на страницы",
    "Your workspace currently has ": "Ваше рабочее пространство в настоящее время имеет ",
    " 0 guests": " 0 гостей",
    "Allow members to request adding guests": "Разрешить участникам запрашивать добавление гостей",
    "Requests must be approved by a workspace owner": "Запросы должны быть одобрены владельцем рабочего пространства",
    "Allow members to request adding other members": "Разрешить участникам запрашивать добавление других участников",
    "Members can submit requests to admins to add more members": "Участники могут отправлять запросы администраторам для добавления больше участников",
    "Domain management": "Управление доменом",
    "Verified domains": "Проверенные домены",
    "Verify ownership of an email domain to access advanced security features including single-sign-on.": "Подтвердите владение доменом электронной почты, чтобы получить доступ к продвинутым функциям безопасности, включая единовременную аутентификацию.",
    "Workspace creation": "Создание рабочего пространства",
    "Customize who can create new workspaces.": "Настройте, кто может создавать новые рабочие пространства.",
    "Claim workspaces": "Заявка на рабочие пространства",
    "Claim workspaces created by users with a verified domain or require owners to use an external domain.": "Претендуйте на рабочие пространства, созданные пользователями с проверенным доменом или требуйте, чтобы владельцы использовали внешний домен.",
    "User management": "Управление пользователями",
    "These settings apply to all users with a verified domain, even if they are not a member of this workspace.": "Эти настройки применяются ко всем пользователям с проверенным доменом, даже если они не являются участниками этого рабочего пространства.",
    "Learn about managed users": "Узнайте о управляемых пользователях",
    "Managed users dashboard": "Панель управляемых пользователей",
    "Manage and view users that are using your verified domains": "Управляйте и просматривайте пользователей, использующих ваши проверенные домены",
    "Allow managed users to change profile information": "Разрешить управляемым пользователям изменять информацию в профиле",
    "Control if managed users can change their preferred name, email address, and profile photo.": "Управляйте возможностью управляемых пользователям изменять предпочтительное имя, адрес электронной почты и фотографию профиля.",
    "External workspace access": "Внешний доступ к рабочему пространству",
    "Control if managed users are able to join workspaces that aren't owned by your organization.": "Управляйте возможностью управляемых пользователям присоединяться к рабочим пространствам, не принадлежащим вашей организации.",
    "Prevent managed users from granting support access": "Запретить управляемым пользователям предоставлять доступ к поддержке",
    "Control if managed users can enable support access on their accounts.": "Управляйте возможностью управляемых пользователям включать доступ к поддержке в своих аккаунтах.",
    "Session duration": "Длительность сессии",
    "Control how long your managed users can be logged in for before they must re-authenticate.": "Управляйте тем, как долго управляемые пользователи могут быть в системе, прежде чем им придется повторно аутентифицироваться.",
    "Log out all users": "Выйти из всех пользователей",
    "Force log out all managed users and require them to re-authenticate.": "Принудительно выйдите из всех управляемых пользователей и требуйте от них повторной аутентификации.",
    "Reset passwords for all users": "Сбросить пароли для всех пользователей",
    "Force reset the passwords for all managed users and require them to create a new one the next time they log in.": "Принудительно сбросьте пароли для всех управляемых пользователей и потребуйте от них создать новый при следующем входе.",
    "SAML Single sign-on (SSO)": "Единовременная аутентификация SAML (SSO)",
    "Learn about SAML SSO": "Узнайте о SAML SSO",
    "Enable SAML SSO": "Включить SAML SSO",
    "Anyone using email addresses with a verified domain can log in via SAML SSO.": "Любой, использующий адреса электронной почты с проверенным доменом, может войти через SAML SSO.",
    "Login method": "Метод входа",
    "Customize how users access SAML SSO-enabled workspaces.": "Настройте, как пользователи получают доступ к рабочим пространствам с включенной SAML SSO.",
    "Automatic account creation": "Автоматическое создание учетной записи",
    "Automatically create Notion accounts for new users who log in via SAML SSO.": "Автоматически создавайте учетные записи Notion для новых пользователей, входящих через SAML SSO.",
    "Linked workspaces": "Связанные рабочие пространства",
    "This SAML SSO configuration applies to the following other workspaces. ": "Эта конфигурация SAML SSO применяется к следующим другим рабочим пространствам. ",
    "Contact support": "Свяжитесь с поддержкой",
    " to add or remove a workspace.": " для добавления или удаления рабочего пространства.",
    "Created at": "Создано",
    "No linked workspaces.": "Нет связанных рабочих пространств.",
    "SCIM provisioning": "Предоставление SCIM",
    "SCIM tokens": "Маркеры SCIM",
    "Generate a token to configure SCIM.": "Сгенерируйте токен для настройки SCIM.",
    "Setup information": "Информация о настройке",
    "Workspace ID": "Идентификатор рабочего пространства",
    "Restrict members from adding connections": "Ограничьте участников в добавлении подключений",
    "Workspace members can install any new connection.": "Участники рабочего пространства могут устанавливать любое новое подключение.",
    "No restrictions": "Без ограничений",
    "All connections": "Все подключения",
    "Users and access": "Пользователи и доступ",
    "Notion Connected App": "Подключенное приложение Notion",
    "Anyone in ": "Любой в ",
    "Slack": "Slack",
    "Import data": "Импорт данных",
    "Import data from other apps and files into Notion": "Импорт данных из других приложений и файлов в Notion",
    "If the app you’re using isn’t listed below, try the ": "Если ваше приложение не указано ниже, попробуйте ",
    "Universal import": "Универсальный импорт",
    "Active Imports": "Активные импорты",
    "Import time": "Время импорта",
    "Import from": "Импорт из",
    "Status": "Статус",
    "There are no ongoing imports associated with your account.": "Нет текущих импортов, связанных с вашим аккаунтом.",
    "View and clone templates into your workspace.": "Просматривайте и клонируйте шаблоны в свое рабочее пространство.",
    "You": "Вы",
    " edited ": " редактировали ",
    "Just now": "Только что",
    "Draft with AI": "Черновик с искусственным интеллектом",
    "Brainstorm ideas…": "Идеи для мозгового штурма...",
    "Blog post…": "Пост блога...",
    "Outline…": "Контур...",
    "Social media post…": "Пост в социальных сетях...",
    "Press release…": "Пресс-релиз...",
    "Creative story…": "Творческий рассказ...",
    "Essay…": "Эссе...",
    "Insert AI blocks": "Вставить блоки искусственного интеллекта",
    "Custom AI block": "Настроенный блок искусственного интеллекта",
    "Recents": "Недавние",
    "Loading cover": "Загрузка обложки",
    "Page Icon": "Значок страницы",
    "Mention a person, page, or date": "Упомяните человека, страницу или дату",
    "Attach file": "Прикрепить файл",
    "Restore deleted pages.": "Восстановить удаленные страницы.",
    "All pages": "Все страницы",
    "In current page": "На текущей странице",
    "Last edited by me": "Последнее редактирование мной",
    "Filter by page title…": "Фильтровать по названию страницы...",
    "No matches found.": "Совпадений не найдено.",
    "Learn about deleting and restoring pages": "Узнать о удалении и восстановлении страниц",
    "Task List": "Список задач",
    "Quick Note": "Быстрая заметка",
    "Getting Started": "Начало работы",
    "New Task": "Новая задача",
    "Take Fig on a walk": "Выгуливайте Фиг в прогулке",
    "Sub Page": "Подстраница",
    "Import from Word, Markdown, HTML, and more.": "Импортировать из Word, Markdown, HTML и других форматов.",
    "Work": "Работа",
    "Search templates": "Поиск шаблонов",
    "Suggested": "Предложенные",
    "Projects & tasks": "Проекты и задачи",
    "Projects, tasks & sprints": "Проекты, задачи и спринты",
    "Meetings": "Встречи",
    "Docs": "Документы",
    "Wiki": "Вики",
    "Product": "Продукт",
    "Product Spec": "Техническое задание на продукт",
    "Product Wiki": "Вики по продукту",
    "Vision and Strategy": "Видение и стратегия",
    "User Research Database": "База данных пользовательских исследований",
    "Product Launch Brief": "Краткое описание запуска продукта",
    "5 more...": "Еще 5...",
    "Blog Editorial Calendar": "Календарь редакционной статьи блога",
    "Campaign Brief": "Краткое описание кампании",
    "Social Media Calendar": "Календарь социальных медиа",
    "Brand Assets": "Брендовые ресурсы",
    "Basic Content Calendar": "Базовый календарь контента",
    "4 more...": "Еще 4...",
    "Engineering": "Инженерия",
    "Engineering Tech Spec": "Техническое задание на инженерию",
    "Engineering Wiki": "Вики по инженерии",
    "Post-mortem": "Анализ после завершения",
    "Retrospective": "Ретроспектива",
    "API Reference": "Справочник по API",
    "2 more...": "Еще 2...",
    "Design": "Дизайн",
    "Design Portfolio": "Портфель дизайна",
    "Design Sprint": "Дизайн-спринт",
    "Design Critique": "Дизайн-критика",
    "UI Design System": "Система дизайна пользовательского интерфейса",
    "Simple Design Moodboard": "Простая дизайн-доска настроения",
    "Startup": "Стартап",
    "Investor update": "Отчет инвесторам",
    "Pitch deck": "Презентация проекта",
    "Funding OS": "Финансирование ОС",
    "Operations": "Операции",
    "Standard Operating Procedure (SOP)": "Стандартные операционные процедуры",
    "Annual Planning": "Годовое планирование",
    "Board Meeting": "Совет директоров",
    "Sales": "Продажи",
    "Sales Wiki": "Продажи Вики",
    "Sales Assets": "Продажи активы",
    "Sales CRM": "Продажи CRM",
    "CRM Tracker": "CRM трекер",
    "Pitch’s sales deal room": "Продажи комната для сделок",
    "Recruiting": "Найм",
    "Interview Guide": "Руководство по собеседованию",
    "Recruiting Tracker": "Трекер по найму",
    "Applicant tracker": "Трекер заявок",
    "Job board": "Доска вакансий",
    "Careers Page": "Страница карьеры",
    "Open Roles Tracker": "Трекер открытых вакансий",
    "HR": "Кадры",
    "Company home": "Домашняя страница компании",
    "Employee Benefits": "Льготы для сотрудников",
    "People Directory": "Справочник людей",
    "New hire onboarding": "Ввод нового сотрудника в должность",
    "Org Chart": "Оргструктура",
    "IT": "ИТ",
    "Vendor Management": "Управление поставщиками",
    "IT Issue Tracker": "Трекер ИТ-проблем",
    "IT Support Center & Issue Tracker": "Центр поддержки ИТ и трекер проблем",
    "IT Change Management Plan": "План управления изменениями ИТ",
    "IT Inventory": "ИТ-инвентаризация",
    "Release Manager": "Менеджер релизов",
    "Individuals": "Личности",
    "1:1 Notes": "Заметки 1:1",
    "Journal": "Журнал",
    "Annual performance self-review": "Ежегодная самооценка результативности",
    "More templates": "Больше шаблонов",
    "Discover thousands of templates made by Notion users like you": "Открывайте тысячи шаблонов, созданных пользователями Notion, такими же, как вы",
    "By Notion": "От Notion",
    "Simple task management — create, organize, and track your tasks. ": "Простое управление задачами — создавайте, организовывайте и отслеживайте свои задачи.",
    "Get template": "Получить шаблон",
    "Tasks": "Задачи",
    "All Tasks": "Все задачи",
    "Board": "Доска",
    "Mine": "Мои",
    "Timeline": "Хронология",
    "Task name": "Название задачи",
    "Assignee": "Исполнитель",
    "Due": "Срок",
    "Write project proposal": "Написать предложение по проекту",
    "Schedule kick-off meeting": "Назначить встречу для старта проекта",
    "Review research results": "Обзор результатов исследования",
    "Brainstorm naming ideas": "Идеи для названия",
    "Book team offsite": "Забронировать внешнюю встречу команды",
    "By project": "По проекту",
    "1 hidden group": "1 скрытая группа",
    "Priority": "Приоритет",
    "Tags": "Метки",
    "Getting started with Projects & tasks": "Начало работы с проектами и задачами",
    "Sample Project: User Education ": "Пример проекта: Обучение пользователей",
    "Sample Project: Performance": "Пример проекта: Производительность",
    "Add a new task": "Добавить новую задачу",
    "Not Started": "Не начато",
    "High": "Высокий",
    "Invite team members": "Пригласить членов команды",
    "Build data dashboards": "Создать информационные панели с данными",
    "Medium": "Средний",
    "Website": "Веб-сайт",
    "In Progress": "В процессе",
    "Mobile": "Мобильное приложение",
    "Done": "Готово",
    "Low": "Низкий",
    "Current Sprint": "Текущий спринт",
    "Sprint planning": "Планирование спринта",
    "Backlog": "Бэклог",
    "Sprint": "Спринт",
    "Project": "Проект",
    "Add filter": "Добавить фильтр",
    "Hidden groups": "Скрытые группы",
    "No Project": "Без проекта",
    "Current": "Текущее",
    "Getting started with Projects, tasks & sprints": "Начало работы с проектами, задачами и спринтами",
    "Summarize research results": "Суммировать результаты исследования",
    "You're all caught up": "Вы в курсе всех событий",
    "You'll be notified here for @mentions, page activity, requests, and page invites.": "Вы будете уведомлены здесь по @упоминаниям, активности на странице, запросам и приглашениям на страницу.",
    "Help, feedback, and ": "Помощь, отзывы и ",
    "keyboard shortcuts": "горячие клавиши",
    "Help & documentation": "Справка и документация",
    "Message support": "Сообщить о проблеме",
    "Keyboard shortcuts": "Горячие клавиши",
    "What's new?": "Что нового?",
    "Join us": "Присоединяйтесь",
    "Twitter – @NotionHQ": "Twitter – @NotionHQ",
    "Terms & privacy": "Условия и конфиденциальность",
    "Updated 22 hours ago": "Обновлено 22 часа назад",
    "/da": "/da",
    "New view": "Новый вид",
    "No data source": "Нет источника данных",
    "Select a data source": "Выберите источник данных",
    " to continue": " для продолжения",
    "Select data source": "Выбрать источник данных",
    "Link or create a database…": "Ссылка или создание базы данных...",
    "New database": "Новая база данных",
    "No results": "Нет результатов",
    "Filter": "Фильтр",
    "Calculate": "Рассчитать",
    "View database": "Просмотр базы данных",
    "Edit database title": "Изменить название базы данных",
    "Hide database title": "Скрыть заголовок базы данных",
    "Edit view layout, grouping and more...": "Изменить макет просмотра, группировку и другое...",
    "View options": "Параметры просмотра",
    "View name": "Название просмотра",
    "Layout": "Макет",
    "Properties": "Свойства",
    "2 shown": "Показаны 2",
    "None": "Нет",
    "Group": "Группа",
    "Sub-items": "Подэлементы",
    "Dependencies": "Зависимости",
    "Load limit": "Лимит загрузки",
    "50 pages": "50 страниц",
    "Automations": "Автоматизация",
    "Lock database": "Заблокировать базу данных",
    "Copy link to view": "Скопировать ссылку для просмотра",
    "Duplicate view": "Дублировать просмотр",
    "Delete view": "Удалить просмотр",
    "Calendar": "Календарь",
    "List": "Список",
    "Table with types to store and view any kind of structured data": "Таблица с типами для хранения и просмотра любого структурированного данных",
    "Show database title": "Показать заголовок базы данных",
    "Show vertical lines": "Показать вертикальные линии",
    "Wrap all columns": "Обернуть все столбцы",
    "Open pages in": "Открыть страницы в",
    "Side peek": "Боковой обзор",
    "Learn about views": "Узнать о просмотрах",
    "Search for a property…": "Поиск свойства...",
    "Shown in table": "Показано в таблице",
    "Hide all": "Скрыть все",
    "New property": "Новое свойство",
    "Learn about properties": "Узнать о свойствах",
    "Search or add new property": "Поиск или добавление нового свойства",
    "AI summary": "Искусственный интеллект: сводка",
    "AI key info": "Искусственный интеллект: ключевая информация",
    "AI custom autofill": "Искусственный интеллект: настраиваемое автозаполнение",
    "AI translation": "Искусственный интеллект: перевод",
    "Type": "Тип",
    "Number": "Число",
    "Multi-select": "Множественный выбор",
    "Person": "Человек",
    "Files & media": "Файлы и медиа",
    "Checkbox": "Флажок",
    "URL": "URL",
    "Email": "Эл. почта",
    "Phone": "Телефон",
    "Formula": "Формула",
    "Relation": "Отношение",
    "Rollup": "Свертка",
    "Created time": "Время создания",
    "Last edited time": "Время последнего редактирования",
    "Last edited by": "Последнее редактирование от",
    "ID": "Идентификатор",
    "GitHub Pull Requests": "Запросы на внесение изменений в GitHub",
    "Google Drive File": "Файл Google Drive",
    "Figma File": "Файл Figma",
    "Zendesk Ticket": "Билет Zendesk",
    "Open as full page": "Открыть как полноэкранный",
    "Add description": "Добавить описание",
    " created ": " создано ",
    " created view ": " создан просмотр ",
    " in ": " в ",
    " created property ": " создано свойство ",
    "No page analytics yet": "Пока нет аналитики страницы",
    "It may take some time for page view information to appear.": "Информация о просмотре страницы может появиться не сразу.",
    "Templates for": "Шаблоны для",
    "Replicate page formats inside this database with templates.": "Реплицировать форматы страниц внутри этой базы данных с помощью шаблонов.",
    "New template": "Новый шаблон",
    "DEFAULT": "ПО УМОЛЧАНИЮ",
    "Back": "Назад",
    "You're editing a template in": "Вы редактируете шаблон в",
    "Press Enter to continue with an empty page.": "Нажмите Enter, чтобы продолжить с пустой страницей.",
    "Filter by…": "Фильтр по...",
    "Add advanced filter": "Добавить расширенный фильтр",
    "Filters": "Фильтры",
    "1 rule": "1 правило",
    "Where": "Где",
    "Contains": "Содержит",
    "Value": "Значение",
    "Add filter rule": "Добавить правило фильтра",
    "Delete filter": "Удалить фильтр",
    "Is": "Является",
    "Is not": "Не является",
    "Does not contain": "Не содержит",
    "Starts with": "Начинается с",
    "Ends with": "Заканчивается на",
    "Is empty": "Пусто",
    "Is not empty": "Не пусто",
    "Turn into group": "Превратить в группу",
    "Add filter group": "Добавить группу фильтров",
    "A group to nest more filters": "Группа для вложения дополнительных фильтров",
    "Create and view automations": "Создавайте и просматривайте автоматизацию",
    "Sort by…": "Сортировать по...",
    "1 filter": "1 фильтр",
    "New sort": "Новая сортировка",
    "Use sub-items to break large items into smaller, more manageable chunks.": "Используйте подэлементы, чтобы разбить крупные элементы на более мелкие и управляемые части.",
    "Parent item": "Родительский элемент",
    "Sub-item": "Подэлемент",
    "Turn on sub-items": "Включить подэлементы",
    "Group by": "Группировать по",
    "Use dependencies to show items that are blocking — or blocked by — other items.": "Используйте зависимости, чтобы показать элементы, которые блокируются или блокируют другие элементы.",
    "Automatic date shifting": "Автоматическое смещение дат",
    "Shift only when dates overlap": "Смещать только при перекрытии дат",
    "Shift & maintain time between items": "Смещать и сохранять время между элементами",
    "Do not automatically shift": "Не смещать автоматически",
    "Avoid weekends": "Избегать выходных",
    "Prevent shifted items from starting or ending on weekends": "Предотвращать начало или завершение смещенных элементов в выходные",
    "Turn on dependencies": "Включить зависимости",
    "New automation": "Новая автоматизация",
    "For pages in": "Для страниц в",
    "When any of these occur": "Когда происходит что-то из перечисленного",
    "Add trigger": "Добавить триггер",
    "Do this": "Выполнить это",
    "Add action": "Добавить действие",
    "Create": "Создать",
    "Discard": "Отменить",
    "Table view of Untitled": "Таблица видов без названия",
    "Open pages on the side. Keeps the view behind interactive.": "Открывает страницы сбоку. Поддерживает интерактивный вид в фоне.",
    "Default for Table": "По умолчанию для таблицы",
    "Center peek": "Центральный обзор",
    "Open pages in a focused, centered modal.": "Открывает страницы в фокусированном центрированном режиме.",
    "Full page": "Полноэкранный режим",
    "Open pages in full page.": "Открывает страницы в полноэкранном режиме.",
    "Count all": "Подсчитать все",
    "Count values": "Подсчитать значения",
    "Count unique values": "Подсчитать уникальные значения",
    "Count empty": "Подсчитать пустые",
    "Count not empty": "Подсчитать непустые",
    "Percent empty": "Процент пустых",
    "Percent not empty": "Процент непустых",
    " edited view ": " отредактировано",
    "1 minute ago": "1 минуту назад",
    "Enter your email address...": "Введите ваш адрес электронной почты...",
    "Logging in to Notion…": "Вход в Notion...",
    "1 backlink": "1 обратная ссылка",
    "Open in Notion's desktop app?": "Открыть в рабочем приложении Notion?",
    "Don't have the app? Download": "Нет приложения? Скачать",
    "Always open in app": "Всегда открывать в приложении",
    "Open in app": "Открыть в приложении",
    "Quickly add a page inside": "Быстро добавьте страницу внутри",
    "Use Notion with your team by creating your first teamspace": "Используйте Notion вместе с командой, создав свое первое рабочее пространство",
    "Free Plan · 1 member": "Бесплатный план · 1 участник",
    "Get Mac app": "Получить приложение для Mac",
    "Search and quickly jump to a page": "Искать и быстро переходить к странице",
    " deleted ": " удалено ",
    "Deleted": "Удалено",
    " created private page ": " создана личная страница ",
    " deleted private page ": " удалена личная страница ",
    "Your workspace has no guests": "В вашем рабочем пространстве нет гостей",
    " tab": " вкладка",
    "Delete, duplicate, and more…": "Удалить, дублировать и многое другое...",
    "This page is in the Trash.": "Эта страница в Корзине.",
    "Restore page": "Восстановить страницу",
    "Delete permanently": "Удалить навсегда",
    "Moved to trash": "Перемещено в корзину",
    "Are you sure you want to delete this page permanently?": "Вы уверены, что хотите удалить эту страницу навсегда?",
    "Yes. Delete this page": "Да, удалить эту страницу",
    "Restore": "Восстановить",
    "How are you planning to use Notion?": "Как вы планируете использовать Notion?",
    "We’ll streamline your setup experience accordingly.": "Мы упростим ваш опыт настройки соответственно.",
    "For my team": "Для моей команды",
    "Collaborate on your docs, projects, and wikis.": "Сотрудничайте над вашими документами, проектами и вики.",
    "For personal use": "Для личного использования",
    "Write better. Think more clearly. Stay organized.": "Пишите лучше. Думайте яснее. Будьте организованными.",
    "For school": "Для учебы",
    "Keep your notes, research, and tasks all in one place.": "Храните свои заметки, исследования и задачи в одном месте.",
    "Continue": "Продолжить",
    "Getting ready…": "Подготовка...",
    "Cornell Notes System": "Система Cornell Notes",
    "Club Homepage": "Домашняя страница клуба",
    "Grade Calculator": "Калькулятор оценок",
    " Welcome to Notion!": " Добро пожаловать в Notion!",
    "Here are the basics:": "Вот основы:",
    "Click anywhere and just start typing": "Щелкните в любом месте и начните печатать",
    "Hit ": "Нажмите ",
    " to see all the types of content you can add - headers, videos, sub pages, etc.": " чтобы увидеть все типы контента, которые вы можете добавить - заголовки, видео, подстраницы и т. д.",
    "Highlight any text, and use the menu that pops up to ": "Выделите любой текст и используйте появляющееся меню, чтобы ",
    "style": "стилизовать ",
    "your": "ваш ",
    "writing": "текст ",
    "however": "как ",
    "you": "вы ",
    "like": "хотите",
    "See the ": "Смотрите ",
    " to the left of this checkbox on hover? Click and drag to move this line": " слева от этого флажка при наведении? Щелкните и перетащите, чтобы переместить эту строку",
    "Click the ": "Нажмите ",
    "+ New Page": " + Новая страница",
    " button at the bottom of your sidebar to add a new page": " кнопку внизу боковой панели, чтобы добавить новую страницу",
    "Click ": "Нажмите ",
    " in your sidebar to get started with pre-built pages": " в вашей боковой панели, чтобы начать с предварительно созданных страниц",
    "This is a toggle block. Click the little triangle to see more useful tips!": "Это переключаемый блок. Нажмите на маленький треугольник, чтобы увидеть больше полезных советов!",
    "Have a question? ": "Есть вопрос? ",
    " at the bottom right for more guides, or to send us a message.": " в правом нижнем углу для получения дополнительных руководств или чтобы отправить нам сообщение.",
    "Introducing Q&A": "Представляем Q&A",
    "Beta": "Бета",
    "Get instant answers to your questions, using information from across your workspace.": "Получайте мгновенные ответы на ваши вопросы, используя информацию из всего вашего рабочего пространства.",
    "Learn more about Q&A": "Узнайте больше о Q&A",
    "Skip": "Пропустить",
    "Request access to Q&A": "Запросить доступ к Q&A",
    "Here are some templates to help you get started": "Вот несколько шаблонов, чтобы помочь вам начать",
    "Use them out of the box, or customize them to your own workflows.": "Используйте их как есть или настройте под свои потребности",
    "OK": "ОК",
    "Clear templates": "Очистить шаблоны",
    "Class Notes": "Заметки по занятиям",
    "Add an account": "Добавить аккаунт",
    "Use an existing account, or sign up with a new email. Your current account will remain logged in.": "Используйте существующий аккаунт или зарегистрируйтесь с новым адресом электронной почты. Ваш текущий аккаунт останется в системе.",
    "Forgot password?": "Забыли пароль?",
    "Personal Home": "Личная страница",
    "Reading List": "Читательский список",
    "Create a team workspace": "Создать рабочее пространство для команды",
    "Fill in some details for your teammates.": "Заполните некоторые детали для ваших командных коллег.",
    "Choose icon": "Выберите значок",
    "Workspace name": "Название рабочего пространства",
    "Acme Inc.": "Acme Inc.",
    "The name of your company or organization.": "Название вашей компании или организации.",
    "Cancel new workspace setup?": "Отменить настройку нового рабочего пространства?",
    "You'll be taken back to your previous workspace.": "Вы вернетесь к предыдущему рабочему пространству.",
    "Back to previous workspace": "Вернуться к предыдущему рабочему пространству",
    "Continue setup": "Продолжить настройку"
  });

  const obj = {}

  const NotionApp = window.document.getElementById('notion-app');

  function getTextNode(node) {
    const sentences = [];

    const _getTextNode = function (node) {
      for (let childNode of node.childNodes) {
        if (childNode instanceof window.Text) {
          if (childNode.data.replace(/[' ']*/, '')) {
            sentences.push(childNode);
          }
        } else if (childNode.placeholder) {
          sentences.push(childNode);
        }
        _getTextNode(childNode);
      }
    };
    _getTextNode(node);
    return sentences;
  }

  function translate(node) {
    const sentences = getTextNode(node);
    for (let text of sentences) {
      const string = text?.data ?? text?.placeholder;
      if (!I18n.ru[string] && /[A-Za-z]/g.test(string)) {
        obj[string] = ''
        console.log(obj)
      }

      if (text?.data && I18n.ru[string]) {
        text.parentNode.replaceChild(new window.Text(I18n.ru[string]), text);
      }
      if (text?.placeholder && I18n.ru[string]) {
        text.setAttribute('placeholder', I18n.ru[string])
      }
    }
  }

  setTimeout(() => {
    window.requestIdleCallback(() => {
      translate(NotionApp);

      const observer = new MutationObserver(function (mutationsList) {
        return window.requestIdleCallback(function () {
          mutationsList = mutationsList.filter(MutationRecord => {
            return MutationRecord.addedNodes.length !== 0;
          }).map(MutationRecord => {
            return MutationRecord.addedNodes;
          });

          for (let nodeList of mutationsList) {
            for (let node of nodeList) {
              translate(node);
            }
          }
        });
      });

      observer.observe(NotionApp, {
        childList: true,
        subtree: true
      });
    });
  });
})();